# Generated by Django 3.2.9 on 2022-02-18 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_subscription_hash_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='hashid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
