# Generated by Django 3.2.9 on 2022-02-18 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='hashid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
