# Generated by Django 3.2.9 on 2022-03-09 00:18

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core', '0008_alter_course_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='CourseOLD',
        ),
    ]
