# Generated by Django 3.2.9 on 2022-03-09 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_course_abc_to_mti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOLD',
        ),
    ]
